spring:
  datasource:
#    username: root
#    password: 1234
#    url: jdbc:mysql://localhost:3306/batch
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false